// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxvtyCfIKeqM2xmVsYmvhCMlVpTwVPs4',
    appId: '1:904030671929:android:d2f1540cd51b4dea9869e8',
    messagingSenderId: '904030671929',
    projectId: 'flutter-sms-auth',
    storageBucket: 'flutter-sms-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr5l6EFOfSJ1-SZ6drBZsCySliZ77pY4A',
    appId: '1:904030671929:ios:f9aada28908217739869e8',
    messagingSenderId: '904030671929',
    projectId: 'flutter-sms-auth',
    storageBucket: 'flutter-sms-auth.appspot.com',
    androidClientId: '904030671929-7ejbfbe50isho55vr72k90sfjp03oh9k.apps.googleusercontent.com',
    iosClientId: '904030671929-ed3dsqji5t8ml1mivh96jbftivilfilp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sms',
  );
}
